package cn.orderMeal.common.model;

import cn.orderMeal.common.model.base.BaseDict;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Dict extends BaseDict<Dict> {
	public static final Dict dao = new Dict().dao();
}
