package cn.orderMeal.common.model;

import cn.orderMeal.common.model.base.BaseDictType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DictType extends BaseDictType<DictType> {
	public static final DictType dao = new DictType().dao();
}
