package cn.orderMeal.common.model;

import cn.orderMeal.common.model.base.BaseDinningTable;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DinningTable extends BaseDinningTable<DinningTable> {
	public static final DinningTable dao = new DinningTable().dao();
}
