package cn.orderMeal.common.model;

import cn.orderMeal.common.model.base.BaseDishType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DishType extends BaseDishType<DishType> {
	public static final DishType dao = new DishType().dao();
}
