package cn.orderMeal.common.model;

import cn.orderMeal.common.model.base.BaseDish;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Dish extends BaseDish<Dish> {
	public static final Dish dao = new Dish().dao();
}
