package cn.orderMeal.common.model;

import cn.orderMeal.common.model.base.BaseGuest;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Guest extends BaseGuest<Guest> {
	public static final Guest dao = new Guest().dao();
}
