package cn.orderMeal.common.model;

import cn.orderMeal.common.model.base.BaseInvotory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Invotory extends BaseInvotory<Invotory> {
	public static final Invotory dao = new Invotory().dao();
}
