package cn.orderMeal.common.model;

import cn.orderMeal.common.model.base.BaseMaterialType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MaterialType extends BaseMaterialType<MaterialType> {
	public static final MaterialType dao = new MaterialType().dao();
}
