package cn.orderMeal.common.model;

import cn.orderMeal.common.model.base.BaseOrderPrint;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderPrint extends BaseOrderPrint<OrderPrint> {
	public static final OrderPrint dao = new OrderPrint().dao();
}
