package cn.orderMeal.common.model;

import cn.orderMeal.common.model.base.BaseOrderItem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderItem extends BaseOrderItem<OrderItem> {
	public static final OrderItem dao = new OrderItem().dao();
}
