package cn.orderMeal.common.model;

import cn.orderMeal.common.model.base.BaseStorageType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class StorageType extends BaseStorageType<StorageType> {
	public static final StorageType dao = new StorageType().dao();
}
