package cn.orderMeal.common.model;

import cn.orderMeal.common.model.base.BaseVipMemberType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VipMemberType extends BaseVipMemberType<VipMemberType> {
	public static final VipMemberType dao = new VipMemberType().dao();
}
