package cn.orderMeal.common.model;

import cn.orderMeal.common.model.base.BaseVipMember;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class VipMember extends BaseVipMember<VipMember> {
	public static final VipMember dao = new VipMember().dao();
}
