package cn.orderMeal.common.model;

import cn.orderMeal.common.model.base.BaseWeixinOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WeixinOrder extends BaseWeixinOrder<WeixinOrder> {
	public static final WeixinOrder dao = new WeixinOrder().dao();
}
