package cn.orderMeal.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseOrderPrint<M extends BaseOrderPrint<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setOrderPrintType(java.lang.String orderPrintType) {
		set("orderPrintType", orderPrintType);
		return (M)this;
	}
	
	public java.lang.String getOrderPrintType() {
		return getStr("orderPrintType");
	}

	public M setOrderId(java.lang.String orderId) {
		set("orderId", orderId);
		return (M)this;
	}
	
	public java.lang.String getOrderId() {
		return getStr("orderId");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

}
