package cn.orderMeal.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDinningTable<M extends BaseDinningTable<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setAcommondate(java.lang.String acommondate) {
		set("acommondate", acommondate);
		return (M)this;
	}
	
	public java.lang.String getAcommondate() {
		return getStr("acommondate");
	}

	public M setStatus(java.lang.String status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}

	public M setDeleteFlag(java.lang.String deleteFlag) {
		set("deleteFlag", deleteFlag);
		return (M)this;
	}
	
	public java.lang.String getDeleteFlag() {
		return getStr("deleteFlag");
	}

	public M setDescription(java.lang.String description) {
		set("description", description);
		return (M)this;
	}
	
	public java.lang.String getDescription() {
		return getStr("description");
	}

	public M setDiningTableNum(java.lang.String diningTableNum) {
		set("diningTableNum", diningTableNum);
		return (M)this;
	}
	
	public java.lang.String getDiningTableNum() {
		return getStr("diningTableNum");
	}

}
