package cn.orderMeal.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseVipMember<M extends BaseVipMember<M>> extends Model<M> implements IBean {

	public M setMobile(java.lang.Integer mobile) {
		set("mobile", mobile);
		return (M)this;
	}
	
	public java.lang.Integer getMobile() {
		return getInt("mobile");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setAddress(java.lang.String address) {
		set("address", address);
		return (M)this;
	}
	
	public java.lang.String getAddress() {
		return getStr("address");
	}

	public M setDeleteFlag(java.lang.Boolean deleteFlag) {
		set("deleteFlag", deleteFlag);
		return (M)this;
	}
	
	public java.lang.Boolean getDeleteFlag() {
		return get("deleteFlag");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("createDate", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("createDate");
	}

	public M setCoins(java.lang.Integer coins) {
		set("coins", coins);
		return (M)this;
	}
	
	public java.lang.Integer getCoins() {
		return getInt("coins");
	}

	public M setVipMemberTypeId(java.lang.String vipMemberTypeId) {
		set("vipMemberTypeId", vipMemberTypeId);
		return (M)this;
	}
	
	public java.lang.String getVipMemberTypeId() {
		return getStr("vipMemberTypeId");
	}

}
