package cn.orderMeal.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseInvotory<M extends BaseInvotory<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setAmount(java.lang.Integer amount) {
		set("amount", amount);
		return (M)this;
	}
	
	public java.lang.Integer getAmount() {
		return getInt("amount");
	}

	public M setStorageTypeId(java.lang.String storageTypeId) {
		set("storageTypeId", storageTypeId);
		return (M)this;
	}
	
	public java.lang.String getStorageTypeId() {
		return getStr("storageTypeId");
	}

	public M setCeateDate(java.util.Date ceateDate) {
		set("ceateDate", ceateDate);
		return (M)this;
	}
	
	public java.util.Date getCeateDate() {
		return get("ceateDate");
	}

	public M setUpdateDate(java.util.Date updateDate) {
		set("updateDate", updateDate);
		return (M)this;
	}
	
	public java.util.Date getUpdateDate() {
		return get("updateDate");
	}

	public M setDeleteFlag(java.lang.Boolean deleteFlag) {
		set("deleteFlag", deleteFlag);
		return (M)this;
	}
	
	public java.lang.Boolean getDeleteFlag() {
		return get("deleteFlag");
	}

	public M setMaterialTypeId(java.lang.String materialTypeId) {
		set("materialTypeId", materialTypeId);
		return (M)this;
	}
	
	public java.lang.String getMaterialTypeId() {
		return getStr("materialTypeId");
	}

}
