package cn.orderMeal.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseOrder<M extends BaseOrder<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setDiningTableId(java.lang.String diningTableId) {
		set("diningTableId", diningTableId);
		return (M)this;
	}
	
	public java.lang.String getDiningTableId() {
		return getStr("diningTableId");
	}

	public M setDeleteFlag(java.lang.String deleteFlag) {
		set("deleteFlag", deleteFlag);
		return (M)this;
	}
	
	public java.lang.String getDeleteFlag() {
		return getStr("deleteFlag");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public M setStatus(java.lang.String status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public M setGuestId(java.lang.String guestId) {
		set("guestId", guestId);
		return (M)this;
	}
	
	public java.lang.String getGuestId() {
		return getStr("guestId");
	}

	public M setDiningTableNum(java.lang.String diningTableNum) {
		set("diningTableNum", diningTableNum);
		return (M)this;
	}
	
	public java.lang.String getDiningTableNum() {
		return getStr("diningTableNum");
	}

	public M setOutTradeNo(java.lang.String outTradeNo) {
		set("outTradeNo", outTradeNo);
		return (M)this;
	}
	
	public java.lang.String getOutTradeNo() {
		return getStr("outTradeNo");
	}

	public M setTotalFee(java.lang.Integer totalFee) {
		set("totalFee", totalFee);
		return (M)this;
	}
	
	public java.lang.Integer getTotalFee() {
		return getInt("totalFee");
	}

	public M setTimeStart(java.util.Date timeStart) {
		set("timeStart", timeStart);
		return (M)this;
	}
	
	public java.util.Date getTimeStart() {
		return get("timeStart");
	}

	public M setTimeExpire(java.util.Date timeExpire) {
		set("timeExpire", timeExpire);
		return (M)this;
	}
	
	public java.util.Date getTimeExpire() {
		return get("timeExpire");
	}

	public M setOpenId(java.lang.String openId) {
		set("openId", openId);
		return (M)this;
	}
	
	public java.lang.String getOpenId() {
		return getStr("openId");
	}

	public M setTransId(java.lang.String transId) {
		set("transId", transId);
		return (M)this;
	}
	
	public java.lang.String getTransId() {
		return getStr("transId");
	}

	public M setTimeEnd(java.util.Date timeEnd) {
		set("timeEnd", timeEnd);
		return (M)this;
	}
	
	public java.util.Date getTimeEnd() {
		return get("timeEnd");
	}

	public M setFinalTotalFee(java.lang.Integer finalTotalFee) {
		set("finalTotalFee", finalTotalFee);
		return (M)this;
	}
	
	public java.lang.Integer getFinalTotalFee() {
		return getInt("finalTotalFee");
	}

	public M setNumberOfDinner(java.lang.Integer numberOfDinner) {
		set("numberOfDinner", numberOfDinner);
		return (M)this;
	}
	
	public java.lang.Integer getNumberOfDinner() {
		return getInt("numberOfDinner");
	}

	public M setDinnerTime(java.util.Date dinnerTime) {
		set("dinnerTime", dinnerTime);
		return (M)this;
	}
	
	public java.util.Date getDinnerTime() {
		return get("dinnerTime");
	}

	public M setPhoneNo(java.lang.String phoneNo) {
		set("phoneNo", phoneNo);
		return (M)this;
	}
	
	public java.lang.String getPhoneNo() {
		return getStr("phoneNo");
	}

}
