package cn.orderMeal.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseGuest<M extends BaseGuest<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setMobile(java.lang.String mobile) {
		set("mobile", mobile);
		return (M)this;
	}
	
	public java.lang.String getMobile() {
		return getStr("mobile");
	}

	public M setAddress(java.lang.String address) {
		set("address", address);
		return (M)this;
	}
	
	public java.lang.String getAddress() {
		return getStr("address");
	}

	public M setDeleteFlag(java.lang.String deleteFlag) {
		set("deleteFlag", deleteFlag);
		return (M)this;
	}
	
	public java.lang.String getDeleteFlag() {
		return getStr("deleteFlag");
	}

	public M setCeateTime(java.util.Date ceateTime) {
		set("ceateTime", ceateTime);
		return (M)this;
	}
	
	public java.util.Date getCeateTime() {
		return get("ceateTime");
	}

	public M setIsVipMember(java.lang.String isVipMember) {
		set("isVipMember", isVipMember);
		return (M)this;
	}
	
	public java.lang.String getIsVipMember() {
		return getStr("isVipMember");
	}

	public M setOpenid(java.lang.String openid) {
		set("openid", openid);
		return (M)this;
	}
	
	public java.lang.String getOpenid() {
		return getStr("openid");
	}

	public M setWechatNickName(java.lang.String wechatNickName) {
		set("wechatNickName", wechatNickName);
		return (M)this;
	}
	
	public java.lang.String getWechatNickName() {
		return getStr("wechatNickName");
	}

	public M setProfilePic(java.lang.String profilePic) {
		set("profilePic", profilePic);
		return (M)this;
	}
	
	public java.lang.String getProfilePic() {
		return getStr("profilePic");
	}

}
