package cn.orderMeal.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseOrder<M extends BaseOrder<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setDiningTableId(java.lang.String diningTableId) {
		set("diningTableId", diningTableId);
		return (M)this;
	}
	
	public java.lang.String getDiningTableId() {
		return getStr("diningTableId");
	}

	public M setDeleteFlag(java.lang.String deleteFlag) {
		set("deleteFlag", deleteFlag);
		return (M)this;
	}
	
	public java.lang.String getDeleteFlag() {
		return getStr("deleteFlag");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public M setStatus(java.lang.String status) {
		set("status", status);
		return (M)this;
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public M setGuestId(java.lang.String guestId) {
		set("guestId", guestId);
		return (M)this;
	}
	
	public java.lang.String getGuestId() {
		return getStr("guestId");
	}

	public M setDiningTabeNum(java.lang.String diningTabeNum) {
		set("diningTabeNum", diningTabeNum);
		return (M)this;
	}
	
	public java.lang.String getDiningTabeNum() {
		return getStr("diningTabeNum");
	}

	public M setOutTradeNo(java.lang.String outTradeNo) {
		set("out_trade_no", outTradeNo);
		return (M)this;
	}
	
	public java.lang.String getOutTradeNo() {
		return getStr("out_trade_no");
	}

}
