package cn.orderMeal.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseWeixinOrder<M extends BaseWeixinOrder<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setAppid(java.lang.String appid) {
		set("appid", appid);
		return (M)this;
	}
	
	public java.lang.String getAppid() {
		return getStr("appid");
	}

	public M setMchId(java.lang.String mchId) {
		set("mch_id", mchId);
		return (M)this;
	}
	
	public java.lang.String getMchId() {
		return getStr("mch_id");
	}

	public M setDeviceInfo(java.lang.String deviceInfo) {
		set("device_info", deviceInfo);
		return (M)this;
	}
	
	public java.lang.String getDeviceInfo() {
		return getStr("device_info");
	}

	public M setNonceStr(java.lang.String nonceStr) {
		set("nonce_str", nonceStr);
		return (M)this;
	}
	
	public java.lang.String getNonceStr() {
		return getStr("nonce_str");
	}

	public M setSign(java.lang.String sign) {
		set("sign", sign);
		return (M)this;
	}
	
	public java.lang.String getSign() {
		return getStr("sign");
	}

	public M setSignType(java.lang.String signType) {
		set("sign_type", signType);
		return (M)this;
	}
	
	public java.lang.String getSignType() {
		return getStr("sign_type");
	}

	public M setResultCode(java.lang.String resultCode) {
		set("result_code", resultCode);
		return (M)this;
	}
	
	public java.lang.String getResultCode() {
		return getStr("result_code");
	}

	public M setErrCode(java.lang.String errCode) {
		set("err_code", errCode);
		return (M)this;
	}
	
	public java.lang.String getErrCode() {
		return getStr("err_code");
	}

	public M setErrCodeDes(java.lang.String errCodeDes) {
		set("err_code_des", errCodeDes);
		return (M)this;
	}
	
	public java.lang.String getErrCodeDes() {
		return getStr("err_code_des");
	}

	public M setOpenid(java.lang.String openid) {
		set("openid", openid);
		return (M)this;
	}
	
	public java.lang.String getOpenid() {
		return getStr("openid");
	}

	public M setIsSubscribe(java.lang.String isSubscribe) {
		set("is_subscribe", isSubscribe);
		return (M)this;
	}
	
	public java.lang.String getIsSubscribe() {
		return getStr("is_subscribe");
	}

	public M setTradeType(java.lang.String tradeType) {
		set("trade_type", tradeType);
		return (M)this;
	}
	
	public java.lang.String getTradeType() {
		return getStr("trade_type");
	}

	public M setBankType(java.lang.String bankType) {
		set("bank_type", bankType);
		return (M)this;
	}
	
	public java.lang.String getBankType() {
		return getStr("bank_type");
	}

	public M setTotalFee(java.lang.Integer totalFee) {
		set("total_fee", totalFee);
		return (M)this;
	}
	
	public java.lang.Integer getTotalFee() {
		return getInt("total_fee");
	}

	public M setSettlementTotalFee(java.lang.Integer settlementTotalFee) {
		set("settlement_total_fee", settlementTotalFee);
		return (M)this;
	}
	
	public java.lang.Integer getSettlementTotalFee() {
		return getInt("settlement_total_fee");
	}

	public M setFeeType(java.lang.String feeType) {
		set("fee_type", feeType);
		return (M)this;
	}
	
	public java.lang.String getFeeType() {
		return getStr("fee_type");
	}

	public M setCashFee(java.lang.Integer cashFee) {
		set("cash_fee", cashFee);
		return (M)this;
	}
	
	public java.lang.Integer getCashFee() {
		return getInt("cash_fee");
	}

	public M setCashFeeType(java.lang.String cashFeeType) {
		set("cash_fee_type", cashFeeType);
		return (M)this;
	}
	
	public java.lang.String getCashFeeType() {
		return getStr("cash_fee_type");
	}

	public M setCouponFee(java.lang.Integer couponFee) {
		set("coupon_fee", couponFee);
		return (M)this;
	}
	
	public java.lang.Integer getCouponFee() {
		return getInt("coupon_fee");
	}

	public M setCouponCount(java.lang.Integer couponCount) {
		set("coupon_count", couponCount);
		return (M)this;
	}
	
	public java.lang.Integer getCouponCount() {
		return getInt("coupon_count");
	}

	public M setCouponType$n(java.lang.String couponType$n) {
		set("coupon_type_$n", couponType$n);
		return (M)this;
	}
	
	public java.lang.String getCouponType$n() {
		return getStr("coupon_type_$n");
	}

	public M setCouponId$n(java.lang.String couponId$n) {
		set("coupon_id_$n", couponId$n);
		return (M)this;
	}
	
	public java.lang.String getCouponId$n() {
		return getStr("coupon_id_$n");
	}

	public M setCouponFee$n(java.lang.Integer couponFee$n) {
		set("coupon_fee_$n", couponFee$n);
		return (M)this;
	}
	
	public java.lang.Integer getCouponFee$n() {
		return getInt("coupon_fee_$n");
	}

	public M setTransactionId(java.lang.String transactionId) {
		set("transaction_id", transactionId);
		return (M)this;
	}
	
	public java.lang.String getTransactionId() {
		return getStr("transaction_id");
	}

	public M setOutTradeNo(java.lang.String outTradeNo) {
		set("out_trade_no", outTradeNo);
		return (M)this;
	}
	
	public java.lang.String getOutTradeNo() {
		return getStr("out_trade_no");
	}

	public M setAttach(java.lang.String attach) {
		set("attach", attach);
		return (M)this;
	}
	
	public java.lang.String getAttach() {
		return getStr("attach");
	}

	public M setTimeEnd(java.lang.String timeEnd) {
		set("time_end", timeEnd);
		return (M)this;
	}
	
	public java.lang.String getTimeEnd() {
		return getStr("time_end");
	}

	public M setOrderId(java.lang.String orderId) {
		set("orderId", orderId);
		return (M)this;
	}
	
	public java.lang.String getOrderId() {
		return getStr("orderId");
	}

}
